// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHdu0GNxHtP4HhEOTvWz9WG0x-_Us5w5E',
    appId: '1:781127490772:web:33e456a873f06790f32f41',
    messagingSenderId: '781127490772',
    projectId: 'teste-3f900',
    authDomain: 'teste-3f900.firebaseapp.com',
    storageBucket: 'teste-3f900.firebasestorage.app',
    measurementId: 'G-VFGHZHJX5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1h_YczpRRSzckrEDespDnWfnRWMTe8o',
    appId: '1:781127490772:android:c3af7ec60dd9fa28f32f41',
    messagingSenderId: '781127490772',
    projectId: 'teste-3f900',
    storageBucket: 'teste-3f900.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClk-OewajCzOC3B5icmbBtw7vCIjDQTRM',
    appId: '1:781127490772:ios:69c53f191ef63baaf32f41',
    messagingSenderId: '781127490772',
    projectId: 'teste-3f900',
    storageBucket: 'teste-3f900.firebasestorage.app',
    iosBundleId: 'com.example.colheitasolidariaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClk-OewajCzOC3B5icmbBtw7vCIjDQTRM',
    appId: '1:781127490772:ios:69c53f191ef63baaf32f41',
    messagingSenderId: '781127490772',
    projectId: 'teste-3f900',
    storageBucket: 'teste-3f900.firebasestorage.app',
    iosBundleId: 'com.example.colheitasolidariaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQWgg9MCTeMmEFJYof3VQ2o9nvcrDgPBE',
    appId: '1:781127490772:web:46da130b4dc49b2bf32f41',
    messagingSenderId: '781127490772',
    projectId: 'teste-3f900',
    authDomain: 'teste-3f900.firebaseapp.com',
    storageBucket: 'teste-3f900.firebasestorage.app',
    measurementId: 'G-NKZF1STR08',
  );

}