// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWlh0m_CxDx9sGoARkmM68EIdsrRC8Fog',
    appId: '1:138444161193:web:94a9b4ba53111821c269b8',
    messagingSenderId: '138444161193',
    projectId: 'colheitasolidaria-teste2',
    authDomain: 'colheitasolidaria-teste2.firebaseapp.com',
    storageBucket: 'colheitasolidaria-teste2.firebasestorage.app',
    measurementId: 'G-6PJZXMZMVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzFwkuSRu5-dhvHWFkBGRVvXyRIdU9mrc',
    appId: '1:138444161193:android:a066d09aef66cb32c269b8',
    messagingSenderId: '138444161193',
    projectId: 'colheitasolidaria-teste2',
    storageBucket: 'colheitasolidaria-teste2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3511HFjvMGTNtugOfU68hYLZ-VDJS3Mc',
    appId: '1:138444161193:ios:a9109a54149879c7c269b8',
    messagingSenderId: '138444161193',
    projectId: 'colheitasolidaria-teste2',
    storageBucket: 'colheitasolidaria-teste2.firebasestorage.app',
    iosClientId: '138444161193-v6cnksmprqeji5cb6ketmnusdvgqr02f.apps.googleusercontent.com',
    iosBundleId: 'com.example.colheitasolidariaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3511HFjvMGTNtugOfU68hYLZ-VDJS3Mc',
    appId: '1:138444161193:ios:a9109a54149879c7c269b8',
    messagingSenderId: '138444161193',
    projectId: 'colheitasolidaria-teste2',
    storageBucket: 'colheitasolidaria-teste2.firebasestorage.app',
    iosClientId: '138444161193-v6cnksmprqeji5cb6ketmnusdvgqr02f.apps.googleusercontent.com',
    iosBundleId: 'com.example.colheitasolidariaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU9vSeWNs1M4qscKyWODFA4Wyy_5H5MIA',
    appId: '1:138444161193:web:e79a15cadf920646c269b8',
    messagingSenderId: '138444161193',
    projectId: 'colheitasolidaria-teste2',
    authDomain: 'colheitasolidaria-teste2.firebaseapp.com',
    storageBucket: 'colheitasolidaria-teste2.firebasestorage.app',
    measurementId: 'G-CKE90B0MT9',
  );

}